name: 生成 Flutter 默认目录

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main

jobs:
  generate_dirs:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置 Flutter 环境
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      # 3. 生成默认 Flutter 目录
      - name: 生成 Flutter 目录
        run: |
          # 如果 pubspec.yaml 不存在，创建一个默认的
          if [ ! -f "pubspec.yaml" ]; then
            cat << 'EOF' > pubspec.yaml
name: private_chat
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
EOF
          fi
          # 生成默认目录
          flutter create . --platforms android,ios

      # 4. 检查生成的文件
      - name: 检查文件结构
        run: |
          ls -la
          ls -la android/
          ls -la ios/

      # 5. 配置 Git 并提交更改
      - name: 提交生成的目录到仓库
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "自动生成 Flutter 默认目录 (android, ios)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}