name: Flutter Android Build

on:
  push:
    branches:
      - main  # 触发构建的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-24.04  # 指定运行环境

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"  # 指定 Flutter 版本，可修改

      - name: 获取 Flutter 依赖
        run: flutter pub get

      - name: 运行 Flutter 代码检查
        run: flutter analyze

      - name: 运行 Flutter 测试
        run: flutter test

      - name: 构建 Release APK
        run: flutter build apk --release

      - name: 上传 APK 作为构件
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk