name: Flutter Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-24.04

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Java 环境
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 设置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: 赋予 Gradle 执行权限
        run: chmod +x android/gradlew

      - name: 清理 Gradle 缓存
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper

      - name: 清理 Flutter 依赖并重新获取
        run: flutter clean && flutter pub get

      - name: 运行 Flutter 代码检查
        run: flutter analyze

      - name: 运行 Flutter 单元测试
        run: flutter test

      - name: 增加 Gradle 内存
        run: echo "org.gradle.jvmargs=-Xmx4096M" >> android/gradle.properties

      - name: 构建 Release APK
        run: flutter build apk --release

      - name: 上传 APK 作为构件
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk