name: 构建并发布 Flutter 应用

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest  # 改为 Linux 环境

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置 Java 环境
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. 设置 Flutter 环境
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      # 4. 清理并生成 Android 目录
      - name: 清理并生成 Android 目录
        run: |
          flutter clean
          flutter create . --platforms android

      # 5. 配置 Android 构建
      - name: 配置 Android 构建
        run: |
          # 写入自定义 android/app/build.gradle
          cat << 'EOF' > android/app/build.gradle
          def localProperties = new Properties()
          def localPropertiesFile = rootProject.file('local.properties')
          if (localPropertiesFile.exists()) {
              localPropertiesFile.withReader('UTF-8') { reader ->
                  localProperties.load(reader)
              }
          }

          def flutterRoot = localProperties.getProperty('flutter.sdk')
          if (flutterRoot == null) {
              throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
          }

          apply plugin: 'com.android.application'
          apply plugin: 'kotlin-android'
          apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

          android {
              compileSdkVersion 34
              sourceSets {
                  main.java.srcDirs += 'src/main/kotlin'
              }
              defaultConfig {
                  applicationId "com.example.private_chat"
                  minSdkVersion 21
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0"
                  multiDexEnabled true
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.debug
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
          }

          flutter {
              source '../..'
          }

          dependencies {
              implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.24"
              implementation 'androidx.multidex:multidex:2.0.1'
          }
          EOF

      # 6. 生成 local.properties
      - name: 生成 local.properties
        run: |
          echo "sdk.dir=$(dirname $(dirname $(which flutter)))/android-sdk" > android/local.properties
          echo "flutter.sdk=$(dirname $(dirname $(which flutter)))" >> android/local.properties

      # 7. 获取依赖
      - name: 获取依赖
        run: flutter pub get

      # 8. 检查文件结构和配置
      - name: 检查文件结构和配置
        run: |
          ls -la
          ls -la android/
          cat android/app/build.gradle
          cat android/local.properties
          cat pubspec.yaml

      # 9. 构建 Android APK
      - name: 构建 Android APK
        run: |
          flutter build apk --release --verbose > build_log.txt 2>&1 || (cat build_log.txt && exit 1)
          cat build_log.txt  # 输出完整构建日志

      # 10. 发布到 GitHub Release
      - name: 发布 APK 到 Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v${{ github.run_number }}
          name: 版本 ${{ github.run_number }}
          body: "自动构建的 APK - 构建于 ${{ github.event.head_commit.timestamp }}"
          token: ${{ secrets.GITHUB_TOKEN }}